@host = https://prgukmsatf.execute-api.us-east-1.amazonaws.com

###
GET {{host}}/products

###
GET {{host}}/products/123

###
POST {{host}}/products
Content-Type: application/json

{
    "name": "Moletom JStack",
    "price": 189.9,
    "tags": ["moleta", "zica do baile"]
}

###
PUT {{host}}/products/123

###
DELETE {{host}}/products/123