@host = https://prgukmsatf.execute-api.us-east-1.amazonaws.com

###
GET {{host}}/products

###
GET {{host}}/products/2ca1cc2b-5772-46b4-8da0-c459c2132d11

###
POST {{host}}/products
Content-Type: application/json

{
    "name": "Moletom JStack",
    "price": 189.9,
    "tags": ["moleta","zica do baile"]
}

###
PUT {{host}}/products/123

###
DELETE {{host}}/products/ee5e0df4-97b5-4b9c-a73f-4999a979e62b